services:
    ajax.flash_messenger:
        class: Ajax\Bundle\FlashMessageBundle\Services\Messenger\Flash
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: kernel.response}